use std::{
    collections::HashMap,
    io::{
        self,
        Read,
        Write,
    }
};

use serde::Deserialize;

use thiserror::Error as ThisError;

use toml::{
    self,
    Value,
    de::Error as TomlError,
};

#[derive(Debug, ThisError)]
pub enum ConfigError {
    #[error("I/O error: {0}")]
    Io(#[from] io::Error),

    #[error("Toml parse error: {0}")]
    Toml(#[from] TomlError),
}

#[derive(Deserialize)]
pub struct Component {
    r#type: String,

    #[serde(flatten)]
    other: HashMap<String, Value>
}

// sizing=Responsive
// buildnumber=1
// color.primary.dark=&HFF303F9F
// color.primary=&HFF3F51B5
// color.accent=&HFFFF4081
// aname=BALL_APP_BARBERAN
// defaultfilescope=App
// main=appinventor.ai_anon7981818875173.BALL_APP_BARBERAN.Screen1
// source=../src
// actionbar=True
// useslocation=False
// assets=../assets
// aiversioning=233
// build=../build
// name=BALL_APP_BARBERAN
// lastopened=Screen1
// showlistsasjson=True
// theme=AppTheme.Light.DarkActionBar
// versioncode=1
// versionname=1.0
// projectcolors={}
#[derive(Deserialize)]
pub struct Configuration {
    name: String,
    internal_name: Option<String>,
    version_id: u32,
    version_name: String,
    use_location: bool,
    components: HashMap<String, Component>
}

impl Configuration {
    pub fn from(stream: &mut impl Read) -> Result<Self, ConfigError> {
        let mut data = String::new();
        stream.read_to_string(&mut data)?;

        Ok(toml::from_str::<'_, Self>(&data)?)
    }
    
    pub fn get_component_type(&self, name: &str) -> Option<String> {
        Some(self.components.get(name)?.r#type.clone())
    }

    pub fn write_project_properties(&self, output: &mut impl Write) -> io::Result<()> {
        let internal_name = self.internal_name.clone().unwrap_or(
            self.name.to_uppercase().chars()
                .map(|c| if c.is_alphanumeric() {c} else {'_'}).collect()
        );

        output.write_all(format!(r#"
        # NOTICE: THIS FILE IS AUTOMATICALLY GENERATED BY AICC. DO NOT MODIFY.
        sizing=Responsive
        buildnumber=1
        color.primary.dark=&HFF303F9F
        color.primary=&HFF3F51B5
        color.accent=&HFFFF4081
        aname={0}
        defaultfilescope=App
        main=appinventor.aicc.{1}.Screen1
        source=../src
        actionbar=True
        useslocation=False
        assets=../assets
        build=../build
        name={1}
        lastopened=Screen1
        showlistsasjson=True
        theme=AppTheme.Light.DarkActionBar
        versioncode={2}
        versionname={3}
        projectcolors={{}}
        "#, self.name, internal_name, self.version_id, self.version_name).as_bytes())
    }
}
